//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Discord_Clone.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Discord_Clone.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  DSIG��GDEF��рvGPOS�/�����GSUBѫ�W���OS/23@~O�`cmap}�j�cvt �&quot;08fpgmW���gasp	�tglyfT��2&apos;���head&quot;o��,6hhean-d$hmtx�{c�loca�*]#h�maxp2S� name���p	WpostF&gt;���prep�w�k 8�B�+C�_&lt;���A�eᜏ�����J���X�����=?EW/�:�X��XK�X^2	CF  � %����V��� [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ggsansmono_Bold {
            get {
                return ResourceManager.GetString("ggsansmono-Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  DSIG��GDEF����vGPOS#����hpGSUBѫ�W���OS/22{o�`cmap}�j�cvt         ///�!�6fpgmW���gasp	��glyf�&apos;|�0head&quot;L��,6hheaLBd$hmtx+�loca;�^�&quot;��maxp�Y� nameO�%��	�postF&gt;�8�prep$e*� 8�B�iI;_&lt;���A�eᜏ����pB���X����p=?HZ/���X��XK�X^2	CF  � %����V��� [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ggsansmono_Normal {
            get {
                return ResourceManager.GetString("ggsansmono-Normal", resourceCulture);
            }
        }
    }
}
